# Generated by Django 5.0.7 on 2024-07-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_avilable", models.BooleanField(default=True)),
            ],
        ),
    ]
